import './globals.css'
import type { ReactNode } from 'react'

export const metadata = {
  title: 'Next.js 15 App',
  description: 'Generated by ChatGPT',
}

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  )
}
